# Q1. Write a function so that the columns of the output matrix are powers of the input vector. The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of (N - i - 1)

In [1]:
import numpy as np


In [2]:
N=5
arr=np.array([1,2,3,4,5])
def my_mat(x):
    return np.column_stack([x**(N-i-1) for i in range(N)])

In [3]:
my_mat(arr)


array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1],
       [625, 125,  25,   5,   1]])

# second method

In [4]:
N=5
arr=np.array([1,2,3,4,5])
def my_mat(x):
    return np.vander(x,N)

In [5]:
my_mat(arr)


array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1],
       [625, 125,  25,   5,   1]])

# Q2. Write a function to find moving average in an array over a window: Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3

In [6]:
l=[3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
n=len(l)
k=int(input('Enter window size: '))
def myfun(l):
    z=[]
    for i in range(n-k+1):
        y=sum(l[i:k+i])/k
        z.append(y)
    return np.array(z)
    
myfun(l)

Enter window size: 6


array([ 5.83333333,  7.16666667, 17.16666667, 28.        , 41.16666667,
       56.33333333, 71.33333333, 94.5       ])